name: Rust

on:
  pull_request:
    types:
      - closed

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docs
      run: cargo doc
